const reportModel = [ 
  "White Blood Cell Count",
  "Red Blood Cell Count",
  "Hemoglobin",
  "Hematocrit",
"Mean Corpuscular Volume (MCV)",
"Mean Corpuscular Hemoglobin (MCH)",
"Mean Corpuscular Hemoglobin Concentration (MCHC)",
"Red Cell Distribution Width (RDW)",
"Platelet Count",
"Mean Platelet Volume (MPV)",
"Neutrophils",
 "Lymphocytes",
"Monocytes",
"Eosinophils",
 "Basophils",
"HbA1c (Glycosylated Hemoglobin)",
 "Pre-Diabetes Range",
"Diabetes Range",
  "Thyroid-Stimulating Hormone (TSH)",
  "Total Thyroxine (T4)",
 "Total Triiodothyronine (T3)",
 "Vitamin A",
"Vitamin B1 (Thiamine)",
 "Vitamin B2 (Riboflavin)",
  "Vitamin B3 (Niacin)",
"Vitamin B5 (Pantothenic Acid)",
  "Vitamin B6 (Pyridoxine)",
"Vitamin B7 (Biotin)",
 "Vitamin B9 (Folate)",
"Vitamin B12 (Cobalamin)",
"Vitamin C",
 "Vitamin D (25-Hydroxy)",
 "Glucose, Fasting (F)",
  "Vitamin E",
 "Vitamin K",
   "Total Cholesterol",
    "High-Density Lipoprotein (HDL) Cholesterol",
    "Low-Density Lipoprotein (LDL) Cholesterol",
      "Very-Low-Density Lipoprotein (VLDL) Cholesterol",
     "Triglycerides",
     "Non-HDL Cholesterol",
  "Alanine Aminotransferase (ALT)",
     "Aspartate Aminotransferase (AST)",
       "Alkaline Phosphatase (ALP)",
     "Gamma-Glutamyl Transferase (GGT)",
    "Total Bilirubin",
     "Direct Bilirubin",
      "Indirect Bilirubin",
      "Total Protein",
      "Albumin",
     "Globulin",
     "Albumin/Globulin Ratio",
   "Lactate Dehydrogenase (LDH)",
     "Blood Urea Nitrogen (BUN)",
      "Creatinine",
      "BUN/Creatinine Ratio",
      "Glomerular Filtration Rate (GFR)",
    "Uric Acid",
     "Sodium",
     "Potassium",
    "Chloride",
      "Carbon Dioxide (Bicarbonate)",
      "Calcium",
     "Phosphorus",
     "Albumin",
    "Total Protein",
   
  ]


module.exports = reportModel

